// <auto-generated />
using System;
using EFChessData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace OnlineChess.Migrations
{
    [DbContext(typeof(ChessDataContext))]
    partial class ChessDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("EFChessData.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentGameSessionGameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("CurrentGameSessionGameSessionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EFChessData.GameSession", b =>
                {
                    b.Property<int>("GameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlackPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhitePlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("GameSessionId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("EFChessData.ObserverPlayer", b =>
                {
                    b.Property<int>("ObserverPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("playerId")
                        .HasColumnType("TEXT");

                    b.HasKey("ObserverPlayerId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("ObserverPlayer");
                });

            modelBuilder.Entity("EFChessData.Account", b =>
                {
                    b.HasOne("EFChessData.GameSession", "CurrentGameSession")
                        .WithMany()
                        .HasForeignKey("CurrentGameSessionGameSessionId");

                    b.Navigation("CurrentGameSession");
                });

            modelBuilder.Entity("EFChessData.ObserverPlayer", b =>
                {
                    b.HasOne("EFChessData.GameSession", null)
                        .WithMany("Observers")
                        .HasForeignKey("GameSessionId");
                });

            modelBuilder.Entity("EFChessData.GameSession", b =>
                {
                    b.Navigation("Observers");
                });
#pragma warning restore 612, 618
        }
    }
}
